services:
  mqtt-broker:
    container_name: mqtt-broker
    image: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - edge-computing

  mqtt-pub:
    container_name: mqtt-pub
    image: health_sensor_pub_img
    restart: always
    networks:
      - edge-computing
    depends_on:
      - mqtt-broker

  data-monitor:
    container_name: data-monitor
    image: patilsweta2008/data-monitor
    restart: always
    networks:
      - edge-computing
    ports:
      - 8080:8083
    depends_on:
      - mqtt-broker

networks:
  edge-computing:
