services:
  mqtt-broker:
    container_name: mqtt-broker
    image: eclipse-mosquitto
    restart: always
    ports:
      - 8883:1883
      - 9001:9001
    extra_hosts:
      - "0.0.0.0:127.0.0.1"  
    volumes: 
      - /Users/swetapatil/BITS/Git/Edge Computing/data-monitor/config/mosquitto.conf:/mosquitto/config/mosquitto.conf 
    networks:
      - edge-computing

  mqtt-pub:
    container_name: mqtt-pub
    image: mqtt-publisher  
    restart: always
    networks:
      - edge-computing
    depends_on:
      - mqtt-broker

  data-monitor:
    container_name: data-monitor
    image: patilsweta2008/data-monitor
    restart: always
    networks:
      - edge-computing
    ports:
      - 8083:8080
    extra_hosts:
      - "0.0.0.0:127.0.0.1"
    depends_on:
      - mqtt-broker

networks:
  edge-computing:
